# Generated by Django 5.1 on 2024-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contentio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logstracking",
            name="user",
        ),
        migrations.AddField(
            model_name="logstracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
